[project]
name = "routeGen"
version = "0.1.0"
description = "A tool to generate route.md of Backend projecto"
readme = "readme.md"
requires-python = ">=3.8"
dependencies = [
    "tree-sitter",
    "tree_sitter_javascript"
]

[project.scripts]
routeGen = "routeGen.main:main"
